name: "Redeploy REPL"
on:
  workflow_run:
    workflows: [Create and publish releases, Publish to npm]
    types: [completed]
    branches: [main]

jobs:
  on-success:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: bigbinary/neeto-commons-repl

      - name: Setup git user
        run: |
          git config user.name "Labeeb Latheef"
          git config user.email "labeeb.latheef@bigbinary.com"

      - name: Create a new empty commit
        run: git commit -m "Trigger deployment" --allow-empty

      - name: Push the commit to main
        uses: ad-m/github-push-action@492de9080c3179a3187bd456763f988f9a06e196
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
          repository: bigbinary/neeto-commons-repl
